config/routes.rb
Rails.application.routes.draw do
  devise_for :users
 resources :items do
 	member do
 		patch :complete
 	end
 end
 root 'items#index'
end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :user

	def completed?
		!completed_at.blank?
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :items
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	before_action :find_item, only: [:show, :edit, :update, :destroy, :complete]
	def index
		if user_signed_in?
			@items = Item.where(:user_id => current_user.id).order("created_at DESC")
		end
	end

	def new
		@item = current_user.items.build
	end

	def create
		@item = current_user.items.build(item_params)
		if @item.save
			redirect_to root_path
		else
			render 'new'
		end
	end

	def show
	end

	def edit
	end

	def update
		if @item.update(item_params)
			redirect_to	item_path(@item)
		else
			render 'edit'
		end
	end

	def destroy
		@item.destroy
		redirect_to root_path
	end

	def complete
		@item.update_attribute(:completed_at, Time.now)
		redirect_to	root_path
	end


	private
	def item_params
		params.require(:item).permit(:title, :description)
	end
	def find_item
		@item = Item.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= simple_form_for @item do |f| %>
	<%= f.input :title, label: 'New Target' %>
	<%= f.input :description, label: 'Describe target' %>
	<%= f.submit %>
<% end %>

app/views/items/_welcome_page.html.erb
<div class="jumbotron">
	<h2>Hit List => Eliminate your Task Targets!</h2>
	<br>
	<h3>Hundreds of Targets eliminated daily, get your life ordered and under control now.</h3>
	<p class="welcome_text">Task Lists are neccessary for a productive and organized life. Unfortunately, they can also be boring. Hit List, boosts your productivity with an entertaining interface.</p>
	<p class="welcome_text">Set your Targets, provide intel, the systematically eliminate them until your objective is complete.</p>
	<%= link_to "Join Us Now!", new_user_registration_path, class: "btn btn-success btn-lg" %>
</div>

app/views/items/edit.html.erb
:<h1>Alter Target</h1>

<%= render 'form' %>
<%= link_to "Delete", method: :delete, data: {confirm: "If you delete this, it cannot be undone. Are you sure you want to eliminate this?"} %>

app/views/items/index.html.erb
<% if user_signed_in? %>
	<h1>List of Verified Targets</h1>
	<% @items.each do |item| %>
		<h2><%= link_to item.title, item %></h2>
		<p><%= item.description %></p>
	<% end %>
<% else %>
	<%= render 'welcome_page' %>
<% end %>

app/views/items/new.html.erb
<div class="col-md-8 col-md-offset-2">
	<h1>New Target</h1>

	<%= render 'form' %>
</div>

app/views/items/show.html.erb
<div class="col-md-10 col-md-offset-1">
	<h2><%= @item.title %></h2>
	<p><%= @item.description %></p>

	<div class="col-md-4 col-md-offset-4">
		<%= link_to "Back", root_path, class: "btn btn-info" %>
		<%= link_to "Alter Target details", edit_item_path, class: "btn btn-default" %>
		<%= link_to "Delete", item_path(@item), method: :delete, data: {confirm: "Are you sure you want to do that, Dave?"} %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hitlist</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<nav class="navbar navbar-default">
		<div class="container">
			<div class="navbar-header">
				<%= link_to "HitList", root_path, class: "navbar-brand" 	%>
			</div>
			<ul class="nav navbar-nav navbar-right">
				<% if current_user.present? %>
				<li><%= link_to "Sign Off", destroy_user_session_path, method: :delete %></li>
				<% else %>
				<li><%= link_to "Sign On", new_user_session_path %></li>
				<li><%= link_to "Sign Up", new_user_registration_path %></li>
				<% end %>
				<% # comment %>
			</ul>
			<% if user_signed_in? %>
				<%= link_to "Add a Target", new_item_path, class: "navbar-text navbar-link" %>
			<% end %>

		</div>

	</nav>

	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

	<div class="container">
		<%= yield %>
	</div>
</body>
</html>